obstacle_range: 4.0
raytrace_range: 5.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.3 # distance a circular robot should be clear of the obstacle
inflation_radius: 0.9
cost_scaling_factor: 2.0

observation_sources: laser_scan_sensor #point_cloud_sensor

min_obstacle_height: 0.0
max_obstacle_height: 5.0

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}