global_costmap:
  global_frame: odom
  robot_base_frame: chassis
  update_frequency: 10.0
  publish_frequency: 10.0
  resolution: 0.05
  static_map: true
  rolling_window: false
  width: 10.0
  height: 10.0
  transform_tolerance: 1.5