base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS #dwa_local_planner/DWAPlannerROS

shutdown_costmaps: false

controller_frequency: 4.0
controller_patience: 5.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.1

conservative_reset_dist: 1.0

recovery_behavior_enabled: true
clearing_rotation_allowed: false
